### ISSUE TITLE
Lab Report 5 Feedback

### ISSUE THREAD

**Issue by farnaf** [leontan29/cse15l-lab-reports#3]
Here is your feedback for Lab Report 5:

- [x] Explains how tests with different results were found (`diff`, manual search, etc)

Test 1:
- [ ] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
  - what was the actual output for Joe's implementation? was it wrong?
- [x] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Test 2:
- [ ] Describes which, if any, implementation is correct by showing both actual outputs and indicating what the expected output is
- [x] Describes bug in code for one of the incorrect implementation and shows the code that should be fixed.

Additional comments from your grader:
nice 😃 
Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by leontan29** [comment]
Could you check if I have implemented the correct changes to get full credit again?

**Comment by farnaf** [comment]
Hi there! I still don't see the output that Joe's implementation produced for test files 495.md and 511.md

Is this the screenshot you meant to include in this report? https://leontan29.github.io/cse15l-lab-reports/report5_image1.png

**Comment by leontan29** [comment]
Hi sorry I used the wrong screenshots!! I'm very sure I have the correct screenshots now

**Comment by leontan29** [comment]
Piazza says that regrades will be available until tomorrow at 5pm. Please let me know if there's anything else I need!
